import type { CultivationPhase } from './types';

export const cultivationPhases: CultivationPhase[] = [
  {
    id: 'ha-canh-gioi',
    name: 'Hạ Cảnh Giới',
    subtitle: 'Đặt nền móng cho con đường tu luyện',
    rankTheme: 'lower',
    levels: [
      {
        id: 'luyen-khi',
        rank: 1,
        name: 'Luyện Khí',
        description: 'Bước đầu thu nạp linh khí từ thiên địa để cải thiện cơ thể.',
        status: 'completed',
        requirements: ['Hoàn thành 3 buổi tập', 'Duy trì chuỗi hoạt động 3 ngày'],
        reward: 'Mở khóa danh hiệu Người nhập môn',
      },
      {
        id: 'truc-co',
        rank: 2,
        name: 'Trúc Cơ',
        description: 'Cải tạo thân thể, xây dựng căn cơ tu luyện, là bước ngoặt quan trọng.',
        status: 'completed',
        requirements: ['Hoàn thành 12 buổi tập', 'Tích lũy 1.000 điểm rèn luyện'],
        reward: 'Mở khóa khung hồ sơ Trúc Cơ',
      },
      {
        id: 'ket-dan',
        rank: 3,
        name: 'Kết Đan',
        description: 'Xuất hiện kim đan, đánh dấu sự kết tinh năng lượng.',
        status: 'current',
        progress: 68,
        requirements: ['Hoàn thành thêm 4 buổi tập', 'Giữ chuỗi hoạt động 7 ngày', 'Đạt 2.500 điểm rèn luyện'],
        reward: 'Mở khóa huy hiệu Kim Đan',
      },
      {
        id: 'nguyen-anh',
        rank: 4,
        name: 'Nguyên Anh',
        description: 'Luyện hồn thành thai, nâng cao khả năng nhận thức.',
        status: 'locked',
        requirements: ['Hoàn thành cảnh giới Kết Đan', 'Duy trì hoạt động 14 ngày'],
        reward: 'Mở khóa huy hiệu Nguyên Anh',
      },
      {
        id: 'hoa-than',
        rank: 5,
        name: 'Hóa Thần',
        description: 'Giai đoạn cao nhất trong Hạ Cảnh Giới, chuẩn bị cho thăng cấp.',
        status: 'locked',
        requirements: ['Hoàn thành cảnh giới Nguyên Anh', 'Tích lũy 10.000 điểm rèn luyện'],
        reward: 'Mở khóa cổng Trung Cảnh Giới',
      },
    ],
  },
  {
    id: 'trung-canh-gioi',
    name: 'Trung Cảnh Giới',
    subtitle: 'Dung hợp sức mạnh và ý chí bền bỉ',
    rankTheme: 'middle',
    levels: [
      {
        id: 'luyen-hu',
        rank: 6,
        name: 'Luyện Hư',
        description: 'Tăng cường sức mạnh và khả năng điều khiển linh khí.',
        status: 'locked',
        requirements: ['Hoàn thành cảnh giới Hóa Thần', 'Duy trì 20 buổi tập trong 30 ngày'],
        reward: 'Mở khóa danh hiệu Luyện Hư',
      },
      {
        id: 'hop-the',
        rank: 7,
        name: 'Hợp Thể',
        description: 'Kết hợp linh hồn và thể xác, đạt được sức mạnh vượt trội.',
        status: 'locked',
        requirements: ['Hoàn thành cảnh giới Luyện Hư', 'Đạt 25.000 điểm rèn luyện'],
        reward: 'Mở khóa khung hồ sơ Hợp Thể',
      },
      {
        id: 'dai-thua',
        rank: 8,
        name: 'Đại Thừa',
        description: 'Cấp độ cao nhất trong Trung Cảnh Giới, có thể làm rung chuyển Thiên Địa.',
        status: 'locked',
        requirements: ['Hoàn thành cảnh giới Hợp Thể', 'Duy trì chuỗi hoạt động 30 ngày'],
        reward: 'Mở khóa cổng Thượng Cảnh Giới',
      },
    ],
  },
  {
    id: 'thuong-canh-gioi',
    name: 'Thượng Cảnh Giới',
    subtitle: 'Một bước vượt qua thiên kiếp, chạm tới tiên giới',
    rankTheme: 'upper',
    levels: [
      {
        id: 'do-kiep',
        rank: 9,
        name: 'Độ Kiếp',
        description: 'Thử thách quyết định xem tu tiên giả có thể thăng cấp lên tiên giới hay không.',
        status: 'locked',
        requirements: ['Hoàn thành cảnh giới Đại Thừa', 'Chinh phục 50.000 điểm rèn luyện', 'Hoàn thành thử thách Thiên Kiếp'],
        reward: 'Danh hiệu Tiên Nhân và quyền năng tối thượng',
      },
    ],
  },
];
